name: Deploy Astro Web

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js (v22 para coincidir con local)
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Astro static site
        run: npm run build

      - name: Sync dist folder to Hetzner
        uses: meingast/rsync-deploy@v0.4.0
        env:
          DEPLOY_KEY: ${{ secrets.HETZNER_SSH_KEY }}
          ARGS: "-avz --delete"
          SERVER_PORT: '22'
          FOLDER: "dist/"
          SERVER_IP: ${{ secrets.HETZNER_HOST }}
          USERNAME: "root"
          TARGET: "/var/www/astro-website"